### ISSUE TITLE
image michaloo/wordpress does not find on docker

### ISSUE THREAD

**Issue by ekanur** [michaloo/dockerpresso#1]
when i run `bash dockerpresso up`, it said "michaloo/wordpress not found". then i change into "michaloo/wordpress-simplified" on docker-compose.yml, and no error message.

**Comment by michaloo** [comment]
Thanks for the report, I will check it in following days.

**Comment by michaloo** [comment]
I took much more "following days" than I expected, but it is finally fixed here:
https://github.com/michaloo/dockerpresso/tree/v0.0.1

Thanks again for the report.
