### ISSUE TITLE
Error establishing database connection

### ISSUE THREAD

**Issue by ekanur** [michaloo/dockerpresso#2]
run `bash dockerpresso up` successfully, also i have copied [wp-cli-environmentalize/templates/env.txt](https://github.com/michaloo/wp-cli-environmentalize/blob/master/templates/env.txt) to my .env file. But appear `Error establishing database connection` on my browser. Would you like to show me right .env configuration??

Thanks

**Comment by michaloo** [comment]
Yes, I've double checked that, and you need to set at least these variables in `.env` file:

> MYSQL_DATABASE=testing
> MYSQL_USER=testing
> MYSQL_PASSWORD=testing
> ...
> MYSQL_ROOT_PASSWORD=testing

then run `bash dockerpresso up`

**Comment by michaloo** [comment]
I've updated the README information. @ekanur if you are still interested in the project let me know if it works for you :)
